---
title: Центр спортивного развития "Старт"
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
description: ЦСР "Старт".
keywords: smolstart,sport-start,sportstart67,github,gh-pages
baseurl: 
url: https://sport-start.github.io
img_path: "/static/assets/img/blog"
author:
  name: sport-start
  first_name: Центр спортивного развития
  last_name: Старт
  avatar: "/static/assets/img/landing/avatar.svg"
  github_username: sport-start
  linkedin_id: jarrekk
  facebook_username: jiakunnj
  twitter_username: jiakun614
  email: me@jarrekk.com
  cv: http://cv.jarrekk.com
  skill_icon1:
  - name: fa-hand-o-down
  - name: fa-arrow-down
  skill_icon2:
  - name: fa-cube
  - name: fa-chevron-circle-down
  desc: Гимнастика для детей в Смоленске.
disqus:
  name: jalpc
ga:
  id: UA-93473370-3
go: 
gio: 
donation: true
index_carousel: true
blog_carousel: true
sass:
  style: compressed
encoding: utf-8
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
